# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9343f0acc033c4617fc01ea9b25015e95870e3928cae20b3b297ae0e426b532981059e4545ad046aa60aee77f3e4adcf15181433d4b33ab261087ac49ae6f367

test:
  secret_key_base: 39823e50a8616d782c22022257d4a373333ce84af4a64137dd23600cc04d29be9adc243600c77909a40cbe5d32b6ffe764eee565350aea164c31635af1651b22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
